In [1]:
from assign_unique_ids_functions import *
import pandas as pd

In [2]:
df = pd.read_csv('../input/il-officers.csv.gz')

In [3]:
df.head()

,Department.Name,PTB.ID,Resignation.Date,Appointed.Date,Race,Birth.Year,Position.Description,First.Name,Last.Name,Middle.Name,Middle.Initial,Suffix.Name
0,Iowa Interstate Railroad Police,65085238,2000-12-20,1989-02-01,WHITE,1954,"Law Enforcement, Full Time",MARK,SANDLER,A,A,NaN
1,Hebron Police Dept,65012972,2010-01-01,1977-04-07,WHITE,1941,"Law Enforcement, Part Time",ROBERT,BUTTON,NaN,NaN,NaN
2,Hebron Police Dept,65017919,2010-01-01,1994-10-24,WHITE,1972,"Law Enforcement, Part Time",ERIC,COLLINS,R,R,NaN
3,Hebron Police Dept,65063914,2010-01-01,1992-05-18,WHITE,1971,"Law Enforcement, Part Time",JOEL,MCNABB,R,R,NaN
4,Johnsburg Police Dept,65008259,NaN,1992-06-09,WHITE,1970,"Law Enforcement, Full Time",DANIEL,BOCKELMANN,A,A,NaN

In [4]:
df.shape

(154645, 12)

In [11]:
dfu = df.drop_duplicates()
dfu.shape

(154590, 12)

In [20]:
keep_duplicates(dfu, ['First.Name', 'Last.Name', 'Middle.Initial', 'Middle.Name', 'Suffix.Name',
          'Birth.Year', 'Race', 'Appointed.Date', 'Resignation.Date', 'PTB.ID'])

,Department.Name,PTB.ID,Resignation.Date,Appointed.Date,Race,Birth.Year,Position.Description,First.Name,Last.Name,Middle.Name,Middle.Initial,Suffix.Name
55798,Wilsonville Police Dept,65007554,2010-01-01,1901-01-01,WHITE,1969,"Law Enforcement, Full Time",AARON,BISHOP,D,D,NaN
128210,Non-Reimbursable Agencies,65007554,2010-01-01,1901-01-01,WHITE,1969,"Law Enforcement, Full Time",AARON,BISHOP,D,D,NaN
55720,Brooklyn Police Dept,65009579,2010-01-01,1997-05-06,BLACK,1927,"Law Enforcement, Part Time",ADLOPH,BRADLEY,NaN,NaN,NaN
55912,Washington Park Police Dept,65009579,2010-01-01,1997-05-06,BLACK,1927,"Law Enforcement, Part Time",ADLOPH,BRADLEY,NaN,NaN,NaN
151945,Kane Co State's Attorney,65103392,NaN,2017-03-16,WHITE,1982,"Law Enforcement, Part Time",ALAN,WEBB,DAVID,D,NaN
151952,Kane Co State's Attorney,65103392,NaN,2017-03-16,WHITE,1982,"Law Enforcement, Full Time",ALAN,WEBB,DAVID,D,NaN
53298,Schaumburg Police Dept,65108931,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",ALDONNA,ZELVIS,NaN,NaN,NaN
84263,Palatine Police Dept,65108931,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",ALDONNA,ZELVIS,NaN,NaN,NaN
85648,Illinois State University Police,65033550,2010-01-01,1901-01-01,WHITE,1959,"Law Enforcement, Full Time",ALFRED,GENTILE,P,P,NaN
101864,Non-Reimbursable Agencies,65033550,2010-01-01,1901-01-01,WHITE,1959,"Law Enforcement, Full Time",ALFRED,GENTILE,P,P,NaN
54316,Cook County Sheriff's Police,65075767,2010-01-01,1901-01-01,WHITE,1966,"Law Enforcement, Full Time",ALICIA,PICKETT,R,R,NaN
77348,Cook County Dept Of Corrections,65075767,2010-01-01,1901-01-01,WHITE,1966,"Law Enforcement, Full Time",ALICIA,PICKETT,R,R,NaN
44099,John A Logan College Police Dept,65030122,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Part Time",AMY,FLETCHER,J,J,NaN
101984,Non-Reimbursable Agencies,65030122,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",AMY,FLETCHER,J,J,NaN
76136,Wheaton Police Dept,65060783,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Part Time",ANTHONY,MARSH,NaN,NaN,NaN
87314,Non-Reimbursable Agencies,65060783,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",ANTHONY,MARSH,NaN,NaN,NaN
64208,London Mills Police Dept,65083143,1991-09-01,1991-08-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",ARCHIE,ROSE,CHARLES,C,NaN
64209,Avon Police Dept,65083143,1991-09-01,1991-08-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",ARCHIE,ROSE,CHARLES,C,NaN
78872,Olympia Fields Police Dept,65061194,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",ARTHUR,MARTINEZ,NaN,NaN,NaN
119413,Non-Reimbursable Agencies,65061194,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",ARTHUR,MARTINEZ,NaN,NaN,NaN
43929,Calumet City Police Dept,65098780,2010-01-01,1901-01-01,WHITE,1901,"Law Enforcement, Part Time",AUTERY,TRIPLETT,L,L,NaN
52274,Calumet Park Police Dept,65098780,2010-01-01,1901-01-01,WHITE,1901,"Law Enforcement, Full Time",AUTERY,TRIPLETT,L,L,NaN
80666,Burnham Police Dept,65060093,2010-01-01,1901-01-01,WHITE,1950,"Law Enforcement, Full Time",BARBARA,MANCINI,NaN,NaN,NaN
82700,Phoenix Police Dept,65060093,2010-01-01,1901-01-01,WHITE,1950,"Law Enforcement, Full Time",BARBARA,MANCINI,NaN,NaN,NaN
108217,Chicago Police Dept,65060093,2010-01-01,1901-01-01,WHITE,1950,"Law Enforcement, Full Time",BARBARA,MANCINI,NaN,NaN,NaN
54592,Non-Reimbursable Agencies,65060800,1998-02-11,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",BILL,MARSHALL,NaN,NaN,NaN
61886,Illinois Dept of Corrections,65060800,1998-02-11,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",BILL,MARSHALL,NaN,NaN,NaN
154131,Pulaski County Sheriff's Office,65125338,NaN,2017-05-31,WHITE,1995,"Law Enforcement, Full Time",BLAINE,CROW,BRITTEN,B,NaN
154133,Pulaski County Sheriff's Office,65125338,NaN,2017-05-31,WHITE,1995,"Law Enforcement, Part Time",BLAINE,CROW,BRITTEN,B,NaN
59378,Wheaton Police Dept,65025442,2010-01-01,1901-01-01,WHITE,1901,"Law Enforcement, Full Time",BONNIE,DRISH,G,G,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
10159,Albers Police Dept,65010613,2002-08-28,1993-07-12,WHITE,1970,"Law Enforcement, Full Time",WENDY,BROMLEY,M,M,NaN
56474,Albers Police Dept,65010613,2002-08-28,1993-07-12,WHITE,1970,"Law Enforcement, Part Time",WENDY,BROMLEY,M,M,NaN
50544,Lisle Police Dept,65004662,2010-01-01,1901-01-01,WHITE,1959,"Law Enforcement, Full Time",WILLIAM,BARNES,G,G,NaN
72217,Wheaton Police Dept,65004662,2010-01-01,1901-01-01,WHITE,1959,"Law Enforcement, Full Time",WILLIAM,BARNES,G,G,NaN
75090,Litchfield Police Dept,65006706,2010-01-01,1901-01-01,WHITE,1956,"Law Enforcement, Full Time",WILLIAM,BERGER,NaN,NaN,NaN
97654,Collinsville Police Dept,65006706,2010-01-01,1901-01-01,WHITE,1956,"Law Enforcement, Full Time",WILLIAM,BERGER,NaN,NaN,NaN
51416,Carlinville Police Dept,65008945,2010-01-01,1993-12-20,WHITE,1967,"Law Enforcement, Part Time",WILLIAM,BORT,F,F,NaN
55717,Brighton Police Dept,65008945,2010-01-01,1993-12-20,WHITE,1967,"Law Enforcement, Part Time",WILLIAM,BORT,F,F,NaN
84146,Carol Stream Police Dept,65016072,2010-01-01,1901-01-01,WHITE,1946,"Law Enforcement, Full Time",WILLIAM,CHESNEY,J,J,NaN
84725,DuPage County Sheriff's Office,65016072,2010-01-01,1901-01-01,WHITE,1946,"Law Enforcement, Full Time",WILLIAM,CHESNEY,J,J,NaN
93772,Bartonville Police Dept,65020232,2010-01-01,1901-01-01,WHITE,1947,Auxiliary (Full and Part Time),WILLIAM,CROWDEN,BOYD,B,NaN
103958,Bartonville Police Dept,65020232,2010-01-01,1901-01-01,WHITE,1947,"Law Enforcement, Full Time",WILLIAM,CROWDEN,BOYD,B,NaN
105443,Pulaski County Sheriff's Office,65044739,2010-01-01,1901-01-01,WHITE,1974,"Law Enforcement, Full Time",WILLIAM,HUDDLESTON,EDWARD,E,NaN
107993,Pulaski Police Department,65044739,2010-01-01,1901-01-01,WHITE,1974,"Law Enforcement, Full Time",WILLIAM,HUDDLESTON,EDWARD,E,NaN
41357,McDonough County Sheriff's Office,65062464,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",WILLIAM,MCCAMANT,NaN,NaN,NaN
87030,Non-Reimbursable Agencies,65062464,2010-01-01,1901-01-01,AMER IND/ALASKAN NATIVE,1901,"Law Enforcement, Full Time",WILLIAM,MCCAMANT,NaN,NaN,NaN
56469,Scott County Sheriff's Office,65077616,2010-01-01,1901-01-01,WHITE,1965,"Law Enforcement, Full Time",WILLIAM,PRICE,J,J,NaN
85026,Havana Police Dept,65077616,2010-01-01,1901-01-01,WHITE,1965,"Law Enforcement, Full Time",WILLIAM,PRICE,J,J,NaN
52204,Litchfield Police Dept,65080212,2010-01-01,1901-01-01,WHITE,1969,"Law Enforcement, Full Time",WILLIAM,RENSING,N,N,NaN
80383,Montgomery County Sheriff's Office,65080212,2010-01-01,1901-01-01,WHITE,1969,"Law Enforcement, Full Time",WILLIAM,RENSING,N,N,NaN
65158,Black Hawk College Police Dept,65086745,2010-01-01,1980-08-11,WHITE,1953,"Law Enforcement, Full Time",WILLIAM,SCHREIBER,H,H,NaN
65159,Orion Police Dept,65086745,2010-01-01,1980-08-11,WHITE,1953,"Law Enforcement, Full Time",WILLIAM,SCHREIBER,H,H,NaN
53932,Bridgeview Police Dept,65088604,2010-01-01,1901-01-01,WHITE,1963,"Law Enforcement, Full Time",WILLIAM,SHEMANSKI,A,A,NaN
54078,Calumet Park Police Dept,65088604,2010-01-01,1901-01-01,WHITE,1963,"Law Enforcement, Full Time",WILLIAM,SHEMANSKI,A,A,NaN
50670,Chicago Police Dept,65003611,2010-01-01,1984-12-31,BLACK,1933,"Law Enforcement, Full Time",WILSON,BAIELY,NaN,NaN,NaN
70735,Metro Water Reclamation District of,65003611,2010-01-01,1984-12-31,BLACK,1933,"Law Enforcement, Full Time",WILSON,BAIELY,NaN,NaN,NaN
4001,Tazewell County Sheriff's Office,65108154,2010-01-01,1982-02-21,WHITE,1936,Auxiliary (Full and Part Time),WINSTON,YATES,NaN,NaN,NaN
38465,Tazewell County Sheriff's Office,65108154,2010-01-01,1982-02-21,WHITE,1936,"Law Enforcement, Full Time",WINSTON,YATES,NaN,NaN,NaN
43398,Bourbonnais Police Dept,65048328,2010-01-01,1901-01-01,WHITE,1973,"Law Enforcement, Full Time",ZACHARY,JOHNSTON,NaN,NaN,NaN
96351,Non-Reimbursable Agencies,65048328,2010-01-01,1901-01-01,WHITE,1973,"Law Enforcement, Full Time",ZACHARY,JOHNSTON,NaN,NaN,NaN

In [21]:
dfu2 = df[['First.Name', 'Last.Name', 'Middle.Initial', 'Middle.Name', 'Suffix.Name',
          'Birth.Year', 'Race', 'Appointed.Date', 'Resignation.Date', 'PTB.ID']].drop_duplicates()

In [22]:
dfu2.shape

(154077, 10)

In [25]:
keep_duplicates(dfu2, ['First.Name', 'Last.Name', 'Middle.Initial', 'Middle.Name', 'Suffix.Name',
          'Birth.Year', 'Race', 'Appointed.Date', 'PTB.ID']).shape

(974, 10)

In [27]:
keep_duplicates(dfu2, ['First.Name', 'Last.Name', 'Middle.Initial', 'Middle.Name', 'Suffix.Name',
          'Birth.Year', 'Race', 'Appointed.Date'])

,First.Name,Last.Name,Middle.Initial,Middle.Name,Suffix.Name,Birth.Year,Race,Appointed.Date,Resignation.Date,PTB.ID
127947,AARON,PICKETT,L,LEE,NaN,1975,WHITE,2010-06-01,2011-05-01,65075766
130547,AARON,PICKETT,L,LEE,NaN,1975,WHITE,2010-06-01,2011-07-14,65075766
139907,ADAM,DURBIN,J,J,NaN,1988,WHITE,2014-02-17,2014-12-24,65111281
142174,ADAM,DURBIN,J,J,NaN,1988,WHITE,2014-02-17,2014-11-05,65111281
142339,ADAM,DURBIN,J,J,NaN,1988,WHITE,2014-02-17,2017-01-31,65111281
37541,ADAM,SKUNDBERG,J,J,NaN,1969,WHITE,1995-05-01,1995-12-31,65090104
38938,ADAM,SKUNDBERG,J,J,NaN,1969,WHITE,1995-05-01,2010-01-01,65090104
124112,ADRIAN,JIGALOV,NaN,NaN,NaN,1975,WHITE,2008-12-09,2011-01-18,65047338
124404,ADRIAN,JIGALOV,NaN,NaN,NaN,1975,WHITE,2008-12-09,2010-09-08,65047338
147687,ADRIENNE,MYERSRAMOS,N,NICOLE,NaN,1979,WHITE,2015-11-09,NaN,65113731
147982,ADRIENNE,MYERSRAMOS,N,NICOLE,NaN,1979,WHITE,2015-11-09,NaN,65120806
35016,ALAN,BARNFIELD,R,R,NaN,1951,WHITE,1995-08-24,2010-01-01,65004708
50885,ALAN,BARNFIELD,R,R,NaN,1951,WHITE,1995-08-24,1996-12-01,65004708
145503,ALAN,GUILFOYLE,NaN,NaN,NaN,1960,WHITE,2015-03-11,2015-06-16,65119700
148290,ALAN,GUILFOYLE,NaN,NaN,NaN,1960,WHITE,2015-03-11,2017-01-04,65119700
6,ALBERT,FRANK,C,C,NaN,1957,WHITE,1991-08-19,1999-02-18,65031189
64295,ALBERT,FRANK,C,C,NaN,1957,WHITE,1991-08-19,1992-05-11,65031189
121891,ALEX,COLLINGE,M,M,NaN,1980,WHITE,2008-04-15,NaN,65017881
123473,ALEX,COLLINGE,M,M,NaN,1980,WHITE,2008-04-15,2014-05-12,65017881
31475,ALFRED,ARNOLD,E,E,NaN,1946,WHITE,1993-01-01,1995-12-31,65002732
38934,ALFRED,ARNOLD,E,E,NaN,1946,WHITE,1993-01-01,NaN,65002732
52580,ALFRED,PAGE,NaN,NaN,NaN,1901,AMER IND/ALASKAN NATIVE,1901-01-01,2010-01-01,65072703
53989,ALFRED,PAGE,NaN,NaN,NaN,1901,AMER IND/ALASKAN NATIVE,1901-01-01,2010-01-01,65072704
74645,ALLEN,BACHMANN,D,D,NaN,1901,AMER IND/ALASKAN NATIVE,1901-01-01,2010-01-01,65003476
83031,ALLEN,BACHMANN,D,D,NaN,1901,AMER IND/ALASKAN NATIVE,1901-01-01,2010-09-16,65003476
35258,ALOYS,DUDRA,P,P,NaN,1953,WHITE,1985-01-01,2007-02-14,65025675
70854,ALOYS,DUDRA,P,P,NaN,1953,WHITE,1985-01-01,1985-11-26,65025675
9418,ANDREW,DENNHARDT,G,G,NaN,1964,WHITE,1989-11-13,2010-01-01,65023216
64159,ANDREW,DENNHARDT,G,G,NaN,1964,WHITE,1989-11-13,1998-06-14,65023216
36683,ANDREW,MONTALBANO,NaN,NaN,NaN,1968,WHITE,1995-08-21,1995-08-21,65066623
...,...,...,...,...,...,...,...,...,...,...
58310,WILLIAM,BURFORD,R,R,NaN,1952,WHITE,1979-01-01,1980-01-01,65012179
60908,WILLIAM,BURFORD,R,R,NaN,1952,WHITE,1979-01-01,2010-01-01,65012179
83269,WILLIAM,CULBERTSON,W,WESLEY,NaN,1968,WHITE,1998-12-16,1999-06-01,65020452
88254,WILLIAM,CULBERTSON,W,WESLEY,NaN,1968,WHITE,1998-12-16,NaN,65020452
62723,WILLIAM,FERRELL,R,RUSSELL,NaN,1947,WHITE,1976-08-01,1976-12-25,65029184
62724,WILLIAM,FERRELL,R,RUSSELL,NaN,1947,WHITE,1976-08-01,2010-01-01,65029184
120826,WILLIAM,GIBSON,H,H,NaN,1974,WHITE,2007-08-10,2007-08-10,65033991
121780,WILLIAM,GIBSON,H,H,NaN,1974,WHITE,2007-08-10,2010-02-08,65033991
96413,WILLIAM,GLISSON,J,J,NaN,1965,WHITE,1990-01-01,1994-01-01,65034600
98357,WILLIAM,GLISSON,J,J,NaN,1965,WHITE,1990-01-01,1995-01-01,65034600
34806,WILLIAM,GRAHAM,J,J,NaN,1941,WHITE,1963-04-29,1995-12-31,65035950
78267,WILLIAM,GRAHAM,J,J,NaN,1941,WHITE,1963-04-29,2010-01-01,65035951
50160,WILLIAM,KELLEY,O,O,NaN,1954,WHITE,1995-05-08,1996-12-31,65050511
54895,WILLIAM,KELLEY,O,O,NaN,1954,WHITE,1995-05-08,1998-09-06,65050511
7608,WILLIAM,MYERS,A,A,NaN,1969,WHITE,1994-07-05,1996-10-02,65068879
86861,WILLIAM,MYERS,A,A,NaN,1969,WHITE,1994-07-05,2010-01-01,65068880
63284,WILLIAM,ODONNELL,NaN,NaN,NaN,1901,AMER IND/ALASKAN NATIVE,1901-01-01,1998-02-11,65071001
75855,WILLIAM,ODONNELL,NaN,NaN,NaN,1901,AMER IND/ALASKAN NATIVE,1901-01-01,2010-01-01,65071001
70170,WILLIAM,PIERCE,J,JOSEPH,NaN,1948,WHITE,1981-11-02,2010-01-01,65075903
70172,WILLIAM,PIERCE,J,JOSEPH,NaN,1948,WHITE,1981-11-02,1981-11-02,65075903
30601,WILLIAM,ROBERTSON,D,D,NaN,1955,WHITE,1982-09-27,2013-04-04,65081868
86960,WILLIAM,ROBERTSON,D,D,NaN,1955,WHITE,1982-09-27,2010-01-01,65081868
48032,WILLIAM,TEGTMEYER,C,C,NaN,1952,WHITE,1988-06-01,1988-11-01,65096536
48797,WILLIAM,TEGTMEYER,C,C,NaN,1952,WHITE,1988-06-01,1992-01-01,65096536
92256,WILLIAM,WHITE,D,D,NaN,1974,WHITE,2000-05-22,2000-11-15,65104760
92336,WILLIAM,WHITE,D,D,NaN,1974,WHITE,2000-05-22,2001-01-01,65104759
5600,WILLIE,LARKS,NaN,NaN,NaN,1942,BLACK,1992-05-11,1997-04-25,65055284
51072,WILLIE,LARKS,NaN,NaN,NaN,1942,BLACK,1992-05-11,1996-02-07,65055284
30996,WILSON,THOMAS,NaN,NaN,NaN,1932,WHITE,1986-05-16,1997-03-15,65097250
55554,WILSON,THOMAS,NaN,NaN,NaN,1932,WHITE,1986-05-16,2010-01-01,65097250

In [43]:
dfu3 = df[['First.Name', 'Last.Name', 'Middle.Initial', 'Middle.Name', 'Suffix.Name',
          'Birth.Year', 'Race', 'Appointed.Date']].drop_duplicates()

In [44]:
keep_duplicates(dfu3, ['First.Name', 'Last.Name', 'Middle.Initial', 'Middle.Name', 'Suffix.Name',
           'Race'])

,First.Name,Last.Name,Middle.Initial,Middle.Name,Suffix.Name,Birth.Year,Race,Appointed.Date
32192,A,CARLOCK,P,PAUL,NaN,1949,WHITE,1986-08-01
59946,A,CARLOCK,P,PAUL,NaN,1949,WHITE,1984-01-01
60350,A,CARLOCK,P,PAUL,NaN,1949,WHITE,1973-07-01
65649,A,CARLOCK,P,PAUL,NaN,1949,WHITE,1982-01-01
82025,A,CARLOCK,P,PAUL,NaN,1949,WHITE,1901-01-01
8962,A,GRIGGS,D,DAVID,NaN,1963,WHITE,1993-11-08
89708,A,GRIGGS,D,DAVID,NaN,1963,WHITE,1999-01-18
141441,AARON,AHART,M,MATHEW,NaN,1986,BLACK,2014-04-04
146485,AARON,AHART,M,MATHEW,NaN,1986,BLACK,2015-11-17
129634,AARON,ANDERSON,J,JACOB,NaN,1989,WHITE,2011-03-02
131401,AARON,ANDERSON,J,JACOB,NaN,1989,WHITE,2010-05-17
137407,AARON,ANDERSON,J,JACOB,NaN,1989,WHITE,2013-06-01
39167,AARON,ANDREW,NaN,NaN,NaN,1972,BLACK,1901-01-01
88856,AARON,ANDREW,NaN,NaN,NaN,1972,BLACK,2000-02-24
104203,AARON,ASKEW,B,B,NaN,1973,WHITE,2003-05-21
105445,AARON,ASKEW,B,B,NaN,1973,WHITE,2003-10-01
118399,AARON,ASKEW,B,B,NaN,1973,WHITE,2007-05-18
140942,AARON,ASKEW,B,B,NaN,1973,WHITE,2014-07-18
141651,AARON,ASKEW,B,B,NaN,1973,WHITE,2014-12-10
142608,AARON,ASKEW,B,B,NaN,1973,WHITE,2014-06-20
145482,AARON,ASKEW,B,B,NaN,1973,WHITE,2015-03-02
137526,AARON,BAKER,L,LOUIS,NaN,1987,BLACK,2012-06-26
154284,AARON,BAKER,L,LOUIS,NaN,1987,BLACK,2016-07-15
34526,AARON,BARIL,S,S,NaN,1971,WHITE,1995-07-02
55777,AARON,BARIL,S,S,NaN,1971,WHITE,1997-03-20
8269,AARON,BEAN,B,B,NaN,1964,WHITE,1989-06-07
35144,AARON,BEAN,B,B,NaN,1964,WHITE,1989-01-03
57833,AARON,BEAN,B,B,NaN,1964,WHITE,1997-08-01
95818,AARON,BEAN,B,B,NaN,1964,WHITE,2001-05-15
103747,AARON,BEAN,B,B,NaN,1964,WHITE,2002-05-08
...,...,...,...,...,...,...,...,...
146278,ZACHARY,ZILLION,W,WILLIAM,NaN,1985,WHITE,2015-09-24
153420,ZACHARY,ZILLION,W,WILLIAM,NaN,1985,WHITE,2016-09-16
125256,ZACHERY,PAGE,J,JOHN,NaN,1985,WHITE,2007-11-11
133895,ZACHERY,PAGE,J,JOHN,NaN,1985,WHITE,2012-03-26
138383,ZACKERY,COOPER,A,A,NaN,1991,WHITE,2013-07-01
141917,ZACKERY,COOPER,A,A,NaN,1991,WHITE,2014-08-03
150658,ZAIRIUS,WEST,D,D,NaN,1992,BLACK,2015-04-02
152145,ZAIRIUS,WEST,D,D,NaN,1992,BLACK,2017-02-06
153348,ZAIRIUS,WEST,D,D,NaN,1992,BLACK,2016-05-15
135700,ZAKARY,ROGY,R,R,NaN,1987,WHITE,2012-12-17
142702,ZAKARY,ROGY,R,R,NaN,1987,WHITE,2014-05-02
142851,ZAKARY,ROGY,R,R,NaN,1987,WHITE,2014-07-28
146582,ZAKARY,ROGY,R,R,NaN,1987,WHITE,2015-03-24
123509,ZAKIYA,LARRY,L,LAISHA,NaN,1981,BLACK,2008-07-14
127839,ZAKIYA,LARRY,L,LAISHA,NaN,1981,BLACK,2009-12-28
137362,ZANE,WITHERS,M,M,NaN,1990,WHITE,2013-07-01
147338,ZANE,WITHERS,M,M,NaN,1990,WHITE,2015-03-01
10656,ZAYE,BASS,D,D,NaN,1963,WHITE,1991-05-10
50484,ZAYE,BASS,D,D,NaN,1963,WHITE,1993-06-24
51396,ZAYE,BASS,D,D,NaN,1963,WHITE,1901-01-01
85964,ZAYE,BASS,D,D,NaN,1963,WHITE,1999-07-23
35928,ZBIGNIEW,ZYWCZYK,R,R,NaN,1952,WHITE,1974-03-01
99016,ZBIGNIEW,ZYWCZYK,R,R,NaN,1952,WHITE,2002-04-29
36573,ZIAD,HAMIDEH,D,D,NaN,1969,WHITE,1995-06-12
54630,ZIAD,HAMIDEH,D,D,NaN,1969,WHITE,1997-03-17
100876,ZIAD,HAMIDEH,D,D,NaN,1969,WHITE,2000-12-14
27057,ZOL,RAINEY,D,D,NaN,1966,BLACK,1994-12-08
45384,ZOL,RAINEY,D,D,NaN,1966,BLACK,1993-02-16
64178,ZORAN,DORIC,NaN,NaN,NaN,1953,WHITE,1986-11-01
64179,ZORAN,DORIC,NaN,NaN,NaN,1953,WHITE,1984-10-24

In [18]:
df[df['Department.Name']=='Chicago Police Dept'].shape

(26747, 12)