In [2]:
import pandas as pd
from assign_unique_ids_functions import *
from merge_functions import *
pd.options.display.max_columns = 1000

In [4]:
prof = pd.read_csv('../input/officer-profiles.csv.gz')
ref = pd.read_csv('../input/officer-reference.csv.gz')

/Users/invinst/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (3,4,11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
awrd = pd.read_csv('../input/awards_demographics.csv.gz')

In [8]:
atr_dict = append_to_reference(sub_df=awrd, ref_df=ref, profile_df=prof, print_merging=True, return_unmatched=True,
                              no_match_cols=['Last.Name', 'Current.Star'], expand_stars=True)

14860 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star9'] columns
10 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star6'] columns
38 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star5'] columns
141 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star4'] columns
479 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star3'] columns
1436 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star2'] columns
7795 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star1'] columns
130 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Current.Star'] columns
1 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'F4FN', 'Star9'] columns
2 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'F4FN', 'Star1'] columns
1 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'F4LN', 'First.Name', 'Star9'] columns
1 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'F4LN', 'First.Name', 'Star3'] columns
5 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'F4LN', 'First.Name', 'Star1'] columns
1 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star2'] columns
3 Matches on
['Gender', 'Middle.Initial2', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star9'] columns
1 Matches on
['Gender', 'Middle.Initial2', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star1'] columns
1 Matches on
['Gender', 'Middle.Initial2', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'F4FN', 'Star9'] columns
1 Matches on
['Gender', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star9'] columns
1 Matches on
['Gender', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star9'] columns
1 Matches on
['Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name', 'Star1'] columns
3 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'First.Name', 'Star9'] columns
3 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'First.Name', 'Star2'] columns
26 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'First.Name', 'Star1'] columns
1 Matches on
['Gender', 'Middle.Initial2', 'Birth.Year', 'Appointed.Date', 'First.Name', 'Star9'] columns
1010 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'First.Name'] columns
1 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'Last.Name', 'F4FN'] columns
2 Matches on
['Gender', 'Middle.Initial2', 'Middle.Initial', 'Birth.Year', 'Appointed.Date', 'F4LN', 'First.Name'] columns
25954 Total Merged. 81.03% of DF1 and 99.33% of DF2 Merged.
6076 Unmerged in DF1. 18.97% Unmerged.
175 Unmerged in DF2. 0.67% Unmerged.

In [9]:
um1 = atr_dict['UM1']
um2 = atr_dict['UM2']

In [17]:
um2[um2['Appointed.Date']<='2016-08-29'].sort_values('Last.Name').head()

,awards_ID,F4FN,First.Name,Star6,Gender,Current.Star,Star8,Middle.Initial2,Star10,Star5,Appointed.Date,Star7,Middle.Initial,F4LN,Birth.Year,Star4,Star2,Star1,Star3,Last.Name,Star9
23802,3410,CARL,CARLOS,NaN,MALE,NaN,NaN,NaN,NaN,NaN,2006-07-16,NaN,P,APAR,1986.0,NaN,NaN,NaN,NaN,APARICIO,NaN
1529,3144,BRIT,BRITTNEY,NaN,FEMALE,NaN,NaN,NaN,NaN,NaN,2010-04-16,NaN,J,BLAC,1985.0,NaN,NaN,NaN,NaN,BLACKWELL,NaN
23904,621,ALIC,ALICIA,NaN,FEMALE,NaN,NaN,NaN,NaN,NaN,2006-07-16,NaN,Y,BLAK,1985.0,NaN,NaN,NaN,NaN,BLAKE,NaN
1836,15434,JONA,JONATHAN,NaN,MALE,NaN,NaN,NaN,NaN,NaN,2010-04-16,NaN,NaN,BOYD,1978.0,NaN,NaN,NaN,NaN,BOYD,NaN
3186,31229,UNDR,UNDREA,NaN,FEMALE,NaN,NaN,NaN,NaN,NaN,2010-09-01,NaN,N,CHAN,1976.0,NaN,NaN,NaN,NaN,CHANDLER,NaN

In [20]:
prof[(prof['First.Name'].str.contains('CARL')) & (prof['Last.Name'].str.contains(''))].sort_values('Appointed.Date')

,UID,Star6,Current.Rank_y,investigators_ID,Current.Rank_x,accused_ID,trr-statuses_ID,Star9,Star1,Suffix.Name,all-sworn_ID,Birth.Year,Star8,Star7,Appointed.Date,Current.Star,Last.Name,trr-officers_ID,Star4,Middle.Initial,Current.Unit,Star10,Star5,all-sworn-units_ID,First.Name,Middle.Initial2,ase-units_ID,all-members_ID,Star3,Race,Gender,Star2,Current.Age
23435,23436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8572.0,NaN,3053.0,1921.0,NaN,NaN,1951-07-30,NaN,RAIMONDO,NaN,NaN,J,12.0,NaN,NaN,3053.0,CARLO,NaN,23193.0,3041.0,NaN,WHITE,MALE,NaN,94.0
31034,31035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3032.0,1922.0,NaN,NaN,1951-10-08,NaN,WILLIS,NaN,NaN,J,171.0,NaN,NaN,3032.0,CARL,NaN,30717.0,3020.0,NaN,BLACK,MALE,NaN,93.0
11489,11490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7008.0,NaN,2987.0,1927.0,NaN,NaN,1953-03-02,NaN,HARNESS,NaN,NaN,C,58.0,NaN,NaN,2987.0,CARL,NaN,11360.0,2975.0,NaN,BLACK,MALE,NaN,88.0
8014,8015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7439.0,NaN,2980.0,1917.0,NaN,NaN,1953-07-23,NaN,ENWELL,NaN,NaN,O,NaN,NaN,NaN,2980.0,CARL,NaN,7924.0,2968.0,NaN,WHITE,MALE,NaN,98.0
17030,17031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3052.0,1927.0,NaN,NaN,1953-09-21,NaN,MAGGIO,NaN,NaN,NaN,701.0,NaN,NaN,3052.0,CARLO,NaN,16853.0,3040.0,NaN,WHITE,MALE,NaN,88.0
27129,27130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3021.0,1926.0,NaN,NaN,1953-09-21,NaN,SONNE,NaN,NaN,S,16.0,NaN,NaN,3021.0,CARL,NaN,26850.0,3009.0,NaN,WHITE,MALE,NaN,89.0
25066,25067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3055.0,1927.0,NaN,NaN,1954-06-16,NaN,RUSSO,NaN,NaN,NaN,NaN,NaN,NaN,3055.0,CARLO,NaN,24806.0,3043.0,NaN,WHITE,MALE,NaN,89.0
7035,7036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2976.0,1929.0,NaN,NaN,1954-10-01,NaN,DOBRICH,NaN,NaN,NaN,145.0,NaN,NaN,2976.0,CARL,NaN,6956.0,2964.0,NaN,WHITE,MALE,NaN,86.0
21601,21602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3009.0,1930.0,NaN,NaN,1955-05-01,NaN,OSTROWSKI,NaN,NaN,E,NaN,NaN,NaN,3009.0,CARL,NaN,21379.0,2997.0,NaN,WHITE,MALE,NaN,86.0
4439,4440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2969.0,1921.0,NaN,NaN,1955-08-22,NaN,CHATMAN,NaN,NaN,NaN,177.0,NaN,NaN,2969.0,CARL,NaN,4388.0,2957.0,NaN,WHITE,MALE,NaN,94.0
17343,17344,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3005.0,1923.0,NaN,NaN,1956-05-16,NaN,MANTELL,NaN,NaN,NaN,NaN,NaN,NaN,3005.0,CARL,NaN,17163.0,2993.0,NaN,WHITE,MALE,NaN,92.0
18887,18888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1752.0,NaN,3007.0,1930.0,NaN,NaN,1956-05-16,NaN,MENCONI,NaN,NaN,J,193.0,NaN,NaN,3007.0,CARL,NaN,18688.0,2995.0,NaN,WHITE,MALE,NaN,85.0
31554,31555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3033.0,1923.0,NaN,NaN,1956-05-16,NaN,YOUNG,NaN,NaN,M,650.0,NaN,NaN,3033.0,CARL,NaN,31233.0,3021.0,NaN,WHITE,MALE,NaN,92.0
7786,7787,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1989.0,NaN,2979.0,1931.0,NaN,NaN,1956-06-01,NaN,EDENFIELD,NaN,NaN,R,22.0,NaN,NaN,2979.0,CARL,NaN,7699.0,2967.0,NaN,WHITE,MALE,NaN,85.0
16432,16433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3001.0,1925.0,NaN,NaN,1956-09-01,NaN,LITURE,NaN,NaN,NaN,125.0,NaN,NaN,3001.0,CARL,NaN,16259.0,2989.0,NaN,WHITE,MALE,NaN,90.0
3790,3791,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3051.0,1928.0,NaN,NaN,1956-09-01,NaN,CANGELOSI,NaN,NaN,M,602.0,NaN,NaN,3051.0,CARLO,NaN,3751.0,3039.0,NaN,WHITE,MALE,NaN,87.0
28904,28905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3026.0,1933.0,NaN,NaN,1957-03-16,NaN,TORRISE,NaN,NaN,NaN,NaN,NaN,NaN,3026.0,CARL,NaN,28609.0,3014.0,NaN,WHITE,MALE,NaN,83.0
8950,8951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16575.0,NaN,2982.0,1935.0,NaN,NaN,1957-11-11,NaN,FORD,NaN,NaN,R,5.0,NaN,NaN,2982.0,CARL,NaN,8851.0,2970.0,NaN,BLACK,MALE,10615.0,80.0
18022,18023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10705.0,SR,3128.0,1931.0,NaN,NaN,1958-02-16,NaN,MCCARL,NaN,NaN,M,NaN,NaN,NaN,3128.0,CARLTON,NaN,17834.0,3116.0,NaN,WHITE,MALE,NaN,84.0
12745,12746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9216.0,NaN,2993.0,1933.0,NaN,NaN,1961-01-09,NaN,HUBER,NaN,NaN,W,176.0,NaN,NaN,2993.0,CARL,NaN,12604.0,2981.0,NaN,WHITE,MALE,NaN,82.0
13530,13531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2556.0,NaN,2996.0,1939.0,NaN,NaN,1961-09-18,NaN,JOHNSON,NaN,NaN,NaN,4.0,NaN,NaN,2996.0,CARL,NaN,13382.0,2984.0,NaN,BLACK,MALE,NaN,76.0
18973,18974,NaN,NaN,NaN,NaN,NaN,NaN,NaN,801.0,NaN,3008.0,1933.0,NaN,NaN,1962-02-19,NaN,MERRITT,NaN,121.0,J,3.0,NaN,64.0,3008.0,CARL,NaN,18770.0,2996.0,386.0,BLACK,MALE,567.0,82.0
7382,7383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.0,NaN,2978.0,1936.0,NaN,NaN,1962-08-13,NaN,DRAMMIS,NaN,NaN,L,140.0,NaN,NaN,2978.0,CARL,NaN,7298.0,2966.0,NaN,WHITE,MALE,NaN,80.0
16919,16920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6935.0,NaN,3003.0,1939.0,NaN,NaN,1963-11-04,NaN,LYZA,NaN,NaN,T,4.0,NaN,NaN,3003.0,CARL,NaN,16742.0,2991.0,NaN,WHITE,MALE,NaN,76.0
27718,27719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3837.0,NaN,3022.0,1937.0,NaN,NaN,1965-03-01,NaN,STOLL,NaN,NaN,B,130.0,NaN,NaN,3022.0,CARL,NaN,27437.0,3010.0,NaN,BLACK,MALE,1538.0,79.0
29417,29418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1089.0,NaN,3115.0,1941.0,NaN,NaN,1966-08-29,NaN,VALLEJO,NaN,NaN,NaN,12.0,NaN,NaN,3115.0,CARLOS,NaN,29114.0,3103.0,NaN,HISPANIC,MALE,NaN,75.0
11536,11537,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10202.0,NaN,2988.0,1944.0,NaN,NaN,1966-11-14,NaN,HARRIS,NaN,NaN,M,3.0,NaN,NaN,2988.0,CARL,NaN,11407.0,2976.0,NaN,BLACK,MALE,NaN,72.0
6741,6742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11564.0,NaN,2975.0,1943.0,NaN,NaN,1967-01-09,NaN,DEMMA,NaN,NaN,J,NaN,NaN,NaN,2975.0,CARL,NaN,6665.0,2963.0,NaN,WHITE,MALE,NaN,72.0
17174,17175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20954.0,NaN,3004.0,1945.0,NaN,NaN,1967-11-13,NaN,MALIK,NaN,NaN,E,620.0,NaN,NaN,3004.0,CARL,NaN,16995.0,2992.0,NaN,WHITE,MALE,20794.0,70.0
30312,30313,NaN,SERGEANT OF POLICE,1297.0,SERGEANT OF POLICE,NaN,NaN,NaN,13364.0,NaN,3030.0,1941.0,NaN,NaN,1967-11-20,NaN,WATSON,NaN,NaN,NaN,142.0,NaN,NaN,3030.0,CARL,NaN,29999.0,3018.0,NaN,BLACK,MALE,868.0,75.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11008,11009,NaN,NaN,NaN,NaN,1684.0,6286.0,NaN,16450.0,NaN,3077.0,1970.0,NaN,NaN,2005-08-29,16450.0,GUEVARA,5569.0,NaN,G,5.0,NaN,NaN,3077.0,CARLOS,NaN,10881.0,3065.0,NaN,HISPANIC,MALE,NaN,45.0
30286,30287,NaN,NaN,NaN,NaN,1659.0,8843.0,NaN,14188.0,NaN,3042.0,1980.0,NaN,NaN,2005-08-29,14188.0,WATKINS,8134.0,NaN,M,3.0,NaN,NaN,3042.0,CARLA,NaN,29973.0,3030.0,NaN,BLACK,FEMALE,NaN,36.0
30257,30258,NaN,SERGEANT OF POLICE,3088.0,SERGEANT OF POLICE,1654.0,8411.0,NaN,14033.0,NaN,3029.0,1977.0,NaN,NaN,2006-01-23,1284.0,WASIELEWSKI,7701.0,NaN,M,11.0,NaN,NaN,3029.0,CARL,NaN,29944.0,3017.0,NaN,WHITE,MALE,1284.0,38.0
19967,19968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3124.0,1974.0,NaN,NaN,2006-05-22,NaN,MUI,NaN,NaN,NaN,44.0,NaN,NaN,3124.0,CARLSON,NaN,19760.0,3112.0,NaN,API,MALE,NaN,41.0
25514,25515,NaN,NaN,NaN,NaN,1709.0,6994.0,NaN,13158.0,NaN,3110.0,1967.0,NaN,NaN,2006-06-26,13158.0,SANTIAGO,6294.0,NaN,M,24.0,NaN,NaN,3110.0,CARLOS,NaN,25248.0,3098.0,NaN,HISPANIC,MALE,NaN,48.0
3720,3721,NaN,NaN,NaN,NaN,1671.0,6931.0,NaN,7055.0,NaN,3063.0,1974.0,NaN,NaN,2006-09-25,7055.0,CAMEYSANDOVAL,6232.0,NaN,R,11.0,NaN,NaN,3063.0,CARLOS,NaN,3681.0,3051.0,NaN,HISPANIC,MALE,NaN,41.0
5862,5863,NaN,NaN,NaN,NaN,1637.0,8930.0,NaN,17479.0,NaN,2974.0,1983.0,NaN,NaN,2006-11-27,17479.0,CUEVAS,8217.0,NaN,J,6.0,NaN,NaN,2974.0,CARL,NaN,5798.0,2962.0,NaN,HISPANIC,MALE,17173.0,32.0
25516,25517,NaN,NaN,NaN,NaN,1710.0,8454.0,NaN,7051.0,NaN,3111.0,1974.0,NaN,NaN,2007-06-04,7051.0,SANTIAGO,7740.0,NaN,A,24.0,NaN,NaN,3111.0,CARLOS,NaN,25249.0,3099.0,NaN,HISPANIC,MALE,NaN,41.0
6853,6854,NaN,NaN,NaN,NaN,1681.0,11242.0,NaN,5206.0,NaN,3074.0,1979.0,NaN,NaN,2007-10-29,5206.0,DIAZ,10528.0,NaN,A,14.0,NaN,NaN,3074.0,CARLOS,NaN,6774.0,3062.0,NaN,HISPANIC,MALE,NaN,37.0
3653,3654,NaN,NaN,NaN,NaN,1721.0,9273.0,NaN,19177.0,NaN,3133.0,1971.0,NaN,NaN,2008-05-19,12456.0,CALHOUN,8568.0,NaN,K,6.0,NaN,NaN,3133.0,CARLYLE,NaN,3614.0,3121.0,12456.0,BLACK,MALE,13537.0,44.0
6670,6671,NaN,NaN,NaN,NaN,1678.0,9189.0,NaN,19182.0,JR,3071.0,1985.0,NaN,NaN,2009-03-09,5284.0,DELATORRE,8478.0,NaN,NaN,6.0,NaN,NaN,3071.0,CARLOS,NaN,6594.0,3059.0,NaN,HISPANIC,MALE,5284.0,31.0
25502,25503,NaN,NaN,NaN,NaN,1707.0,9474.0,NaN,9919.0,NaN,3108.0,1977.0,NaN,NaN,2010-04-16,9919.0,SANTAMARIA,8778.0,NaN,NaN,3.0,NaN,NaN,3108.0,CARLOS,NaN,25235.0,3096.0,NaN,HISPANIC,MALE,NaN,38.0
23538,23539,NaN,NaN,NaN,NaN,1699.0,10180.0,NaN,13455.0,JR,3098.0,1975.0,NaN,NaN,2010-04-22,12046.0,RAMOS,8946.0,NaN,NaN,5.0,NaN,NaN,3098.0,CARLOS,NaN,23296.0,3086.0,NaN,HISPANIC,MALE,12046.0,40.0
6684,6685,NaN,NaN,NaN,NaN,1680.0,9967.0,NaN,7561.0,NaN,3073.0,1978.0,NaN,NaN,2011-10-17,2814.0,DELGADO,9288.0,NaN,A,11.0,NaN,NaN,3073.0,CARLOS,NaN,6608.0,3061.0,NaN,HISPANIC,MALE,2814.0,38.0
25001,25002,NaN,NaN,NaN,NaN,NaN,11347.0,NaN,13526.0,NaN,3103.0,1979.0,NaN,NaN,2012-11-30,13526.0,RUIZ,10629.0,NaN,R,10.0,NaN,NaN,3103.0,CARLOS,NaN,24742.0,3091.0,NaN,HISPANIC,MALE,NaN,36.0
1375,1376,NaN,NaN,NaN,NaN,1668.0,10690.0,NaN,16054.0,NaN,3060.0,1985.0,NaN,NaN,2013-05-01,16054.0,BARONA,9998.0,NaN,E,7.0,NaN,NaN,3060.0,CARLOS,NaN,1355.0,3048.0,NaN,HISPANIC,MALE,NaN,30.0
4184,4185,NaN,NaN,NaN,NaN,1674.0,NaN,NaN,11674.0,NaN,3066.0,1974.0,NaN,NaN,2013-06-03,11674.0,CASTILLO,NaN,NaN,H,15.0,NaN,NaN,3066.0,CARLOS,NaN,4134.0,3054.0,NaN,HISPANIC,MALE,NaN,41.0
1618,1619,NaN,NaN,NaN,NaN,1670.0,11560.0,NaN,17818.0,NaN,3062.0,1974.0,NaN,NaN,2013-07-15,17818.0,BECERRIL,10845.0,NaN,NaN,10.0,NaN,NaN,3062.0,CARLOS,NaN,1596.0,3050.0,NaN,HISPANIC,MALE,NaN,41.0
20833,20834,NaN,NaN,NaN,NaN,NaN,11535.0,NaN,18571.0,NaN,3092.0,1984.0,NaN,NaN,2013-12-02,18571.0,NUNEZ,10818.0,NaN,E,10.0,NaN,NaN,3092.0,CARLOS,NaN,20615.0,3080.0,NaN,HISPANIC,MALE,NaN,32.0
22156,22157,NaN,NaN,NaN,NaN,1648.0,11013.0,NaN,18585.0,NaN,3011.0,1981.0,NaN,NaN,2014-02-18,18585.0,PAWLOWSKI,10298.0,NaN,M,3.0,NaN,NaN,3011.0,CARL,NaN,21932.0,2999.0,NaN,WHITE,MALE,NaN,34.0
23178,23179,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16902.0,NaN,3012.0,1983.0,NaN,NaN,2014-04-28,NaN,PRUITT,NaN,NaN,A,2.0,NaN,NaN,3012.0,CARL,NaN,22938.0,3000.0,NaN,BLACK,MALE,NaN,33.0
31503,31504,NaN,NaN,NaN,NaN,1716.0,11415.0,NaN,16022.0,JR,3120.0,1981.0,NaN,NaN,2014-08-25,16022.0,YANEZ,10698.0,NaN,A,7.0,NaN,NaN,3120.0,CARLOS,NaN,31184.0,3108.0,NaN,HISPANIC,MALE,NaN,34.0
21530,21531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17872.0,NaN,3094.0,1990.0,NaN,NaN,2014-09-29,NaN,ORTIZ,NaN,NaN,C,6.0,NaN,NaN,3094.0,CARLOS,NaN,21308.0,3082.0,NaN,HISPANIC,MALE,NaN,25.0
13531,13532,NaN,NaN,NaN,NaN,NaN,11494.0,NaN,15230.0,NaN,2997.0,1990.0,NaN,NaN,2014-10-27,15230.0,JOHNSON,10779.0,NaN,L,5.0,NaN,NaN,2997.0,CARL,NaN,13381.0,2985.0,NaN,BLACK,MALE,NaN,25.0
4102,4103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17079.0,NaN,3046.0,1990.0,NaN,NaN,2015-08-31,NaN,CASASANTO,NaN,NaN,M,44.0,NaN,NaN,3046.0,CARLIE,NaN,4055.0,3034.0,NaN,WHITE,FEMALE,NaN,25.0
22309,22310,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3040.0,1989.0,NaN,NaN,2015-08-31,NaN,PENTIMONE,NaN,NaN,A,44.0,NaN,NaN,3040.0,CARLA,NaN,22081.0,3028.0,NaN,WHITE,FEMALE,NaN,27.0
29573,29574,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3117.0,1983.0,NaN,NaN,2015-12-14,NaN,VEGA,NaN,NaN,NaN,44.0,NaN,NaN,3117.0,CARLOS,NaN,29269.0,3105.0,NaN,HISPANIC,MALE,NaN,32.0
12133,12134,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3081.0,1985.0,NaN,NaN,2016-02-29,NaN,HERRERA,NaN,NaN,NaN,44.0,NaN,NaN,3081.0,CARLOS,NaN,NaN,3069.0,NaN,HISPANIC,MALE,NaN,NaN
4927,4928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3132.0,1991.0,NaN,NaN,2016-06-27,NaN,COFFMAN,NaN,NaN,R,44.0,NaN,NaN,3132.0,CARLY,NaN,NaN,3120.0,NaN,WHITE,FEMALE,NaN,NaN
2572,2573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3131.0,1991.0,NaN,NaN,2016-06-27,NaN,BRACKIN,NaN,NaN,V,44.0,NaN,NaN,3131.0,CARLY,NaN,NaN,3119.0,NaN,HISPANIC,FEMALE,NaN,NaN