In [1]:
import pandas as pd
import os
from assign_unique_ids_functions import *
import numpy as np

In [2]:
df = pd.read_csv("../input/all-members.csv.gz")

In [3]:
print(df.shape)
df.head()

(31933, 10)

,Rank,Birth.Year,Gender,Appointed.Date,Race,Last.Promotion.Date,Last.Name,Suffix.Name,First.Name,Middle.Initial
0,SERGEANT OF POLICE,1971,MALE,2005-09-26,WHITE,2016-06-01,AARON,NaN,JEFFERY,M
1,POLICE OFFICER,1980,FEMALE,2005-09-26,HISPANIC,2005-09-26,AARON,NaN,KARINA,NaN
2,POLICE OFFICER,1942,MALE,1970-06-15,WHITE,1970-06-15,ABATE,NaN,DANIEL,P
3,POLICE OFFICER,1968,MALE,1994-12-05,WHITE,1994-12-05,ABBATE,NaN,ANTHONY,G
4,PO AS DETECTIVE,1942,MALE,1969-01-06,WHITE,1969-01-06,ABBATE,NaN,CARMEL,G

In [5]:
kd = keep_duplicates(df, ["First.Name", "Last.Name", "Birth.Year", "Appointed.Date"])
kd

,Rank,Birth.Year,Gender,Appointed.Date,Race,Last.Promotion.Date,Last.Name,Suffix.Name,First.Name,Middle.Initial
14017,POLICE OFFICER,1970,FEMALE,1999-05-10,WHITE,1999-05-10,JURCZYKOWSKI,NaN,AUDREY,A
14018,POLICE OFFICER,1970,FEMALE,1999-05-10,WHITE,NaN,JURCZYKOWSKI,NaN,AUDREY,NaN
29847,POLICE OFFICER,1976,MALE,1999-05-10,WHITE,1999-05-11,VONKONDRAT,NaN,ERICK,M
29848,POLICE OFFICER,1976,MALE,1999-05-10,WHITE,NaN,VONKONDRAT,NaN,ERICK,NaN
1258,POLICE OFFICER,1983,MALE,2009-12-16,WHITE,2009-12-16,BANSLEY,NaN,JAMES,A
1259,POLICE OFFICER,1983,MALE,2009-12-16,WHITE,2009-12-16,BANSLEY,NaN,JAMES,H
1803,POLICE OFFICER,1976,MALE,1999-10-25,BLACK,NaN,BENTLEY,NaN,JOEL,A
1804,POLICE OFFICER,1976,MALE,1999-10-25,WHITE,1999-10-25,BENTLEY,NaN,JOEL,A
24718,POLICE OFFICER,1968,MALE,1999-06-21,HISPANIC,NaN,ROMO,NaN,JORGE,NaN
24719,POLICE OFFICER,1968,MALE,1999-06-21,HISPANIC,1999-06-21,ROMO,NaN,JORGE,NaN
4375,POLICE OFFICER,1972,MALE,2000-01-24,BLACK,2000-01-24,CHAMBERS,NaN,JOSE,A
4376,POLICE OFFICER,1972,MALE,2000-01-24,BLACK,NaN,CHAMBERS,NaN,JOSE,A
640,POLICE OFFICER,1948,MALE,1970-01-19,WHITE,1970-04-19,ANDERSON,NaN,ROBERT,J
641,POLICE OFFICER,1948,MALE,1970-01-19,WHITE,1970-01-19,ANDERSON,NaN,ROBERT,M
1404,SERGEANT OF POLICE,1926,MALE,1950-06-03,WHITE,1962-10-16,BARRETT,NaN,ROBERT,E
1405,LIEUTENANT OF POLICE,1926,MALE,1950-06-03,WHITE,1977-10-16,BARRETT,NaN,ROBERT,J
26962,PO AS DETECTIVE,1947,MALE,1971-02-22,WHITE,1971-02-22,SMITH,NaN,ROBERT,E
26963,POLICE OFFICER,1947,MALE,1971-02-22,WHITE,1971-02-22,SMITH,NaN,ROBERT,E
20293,POLICE OFFICER,1962,MALE,2000-09-11,WHITE,2000-09-11,MYTHEN,NaN,STEPHEN,C
20294,POLICE OFFICER,1962,MALE,2000-09-11,WHITE,NaN,MYTHEN,NaN,STEPHEN,NaN
29510,POLICE OFFICER,1981,MALE,2005-12-05,HISPANIC,2005-12-05,VARGAS,NaN,THOMAS,NaN
29511,POLICE OFFICER,1981,MALE,2005-12-05,HISPANIC,NaN,VARGAS,NaN,THOMAS,NaN
20904,PO AS DETECTIVE,1967,MALE,1995-01-03,WHITE,1995-01-03,OBRIEN,NaN,TIMOTHY,P
20915,PO AS DETECTIVE,1967,MALE,1995-01-03,WHITE,1995-01-03,OBRIEN,NaN,TIMOTHY,J
15622,POLICE OFFICER,1976,MALE,2003-09-29,WHITE,2003-09-29,LACZ,NaN,WOJCIECH,NaN
15623,UNKNOWN,1976,MALE,2003-09-29,WHITE,NaN,LACZ,NaN,WOJCIECH,NaN

In [8]:
kd.to_csv('AM_possible_duplicates.csv')

In [26]:
id_cols = ["First.Name", "Last.Name","Middle.Initial", "Suffix.Name","Race", "Gender", "Birth.Year", "Appointed.Date", "Rank", "Last.Promotion.Date"]

In [27]:
df = assign_unique_ids(df, id_cols)

In [28]:
df

,Race,Gender,Appointed.Date,Birth.Year,Rank,Last.Promotion.Date,Last.Name,Suffix.Name,First.Name,Middle.Initial,TID
0,WHITE,MALE,2005-09-26,1971,SERGEANT OF POLICE,2016-06-01,AARON,NaN,JEFFERY,M,1
1,HISPANIC,FEMALE,2005-09-26,1980,POLICE OFFICER,2005-09-26,AARON,NaN,KARINA,NaN,2
2,WHITE,MALE,1970-06-15,1942,POLICE OFFICER,1970-06-15,ABATE,NaN,DANIEL,P,3
3,WHITE,MALE,1994-12-05,1968,POLICE OFFICER,1994-12-05,ABBATE,NaN,ANTHONY,G,4
4,WHITE,MALE,1969-01-06,1942,PO AS DETECTIVE,1969-01-06,ABBATE,NaN,CARMEL,G,5
5,WHITE,MALE,1954-10-16,1930,SERGEANT OF POLICE,1971-08-01,ABBATE,NaN,CARMEN,S,6
6,WHITE,MALE,1995-12-04,1972,POLICE OFFICER,1995-12-04,ABBATE,NaN,TERRY,M,7
7,BLACK,MALE,1949-03-16,1923,LIEUTENANT OF POLICE,1975-03-16,ABBEY,NaN,LEON,NaN,8
8,BLACK,MALE,1990-03-26,1945,POLICE OFFICER,1990-03-26,ABBEY,NaN,LEON,B,9
9,BLACK,MALE,1976-04-26,1952,POLICE OFFICER,1973-10-22,ABBEY,NaN,MICHAEL,J,10
10,WHITE,MALE,1970-12-14,1949,PO AS DETECTIVE,1970-12-14,ABBOTT,NaN,ANDREW,A,11
11,WHITE,MALE,1982-11-29,1953,POLICE OFFICER,1982-11-29,ABBOTT,NaN,DALE,E,12
12,WHITE,FEMALE,1987-12-07,1958,POLICE OFFICER,1987-12-07,ABBOTT,NaN,ELIZABETH,L,13
13,WHITE,FEMALE,1986-07-14,1965,PO AS DETECTIVE,1986-07-14,ABBOTT,NaN,LAURA,F,14
14,WHITE,MALE,2012-11-30,1983,POLICE OFFICER,2012-11-30,ABDALLAH,NaN,ZAID,F,15
15,WHITE,MALE,2006-12-18,1978,POLICE OFFICER,2006-12-18,ABDELHADI,NaN,ABDALMAHD,NaN,16
16,API,MALE,2008-04-28,1984,POLICE OFFICER,2008-04-28,ABDELMAJEID,NaN,AZIZ,NaN,17
17,BLACK,MALE,1989-12-26,1958,POLICE OFFICER,1989-12-26,ABDULLAH,NaN,MOULAY,R,18
18,API,MALE,1999-10-25,1976,POLICE OFFICER,1999-10-25,ABEJERO,NaN,JASON,V,19
19,API,MALE,1999-12-13,1949,POLICE OFFICER,1999-12-13,ABEJERO,NaN,RESTITUTO,E,20
20,WHITE,MALE,1970-06-15,1949,SERGEANT OF POLICE,2001-06-01,ABELS,NaN,KENNETH,L,21
21,WHITE,FEMALE,1985-09-09,1957,POLICE OFFICER,1986-11-01,ABELSON,NaN,DEBORAH,M,22
22,BLACK,MALE,1964-06-08,1937,PO AS DETECTIVE,1964-07-23,ABINGTON,NaN,EUGENE,B,23
23,WHITE,MALE,2015-06-29,1990,POLICE OFFICER,2015-06-29,ABNEY,NaN,PATRICK,R,24
24,WHITE,MALE,1947-12-22,1925,LIEUTENANT OF POLICE,NaN,ABRAHAM,NaN,JOHN,NaN,25
25,WHITE,MALE,1950-04-03,1922,UNKNOWN,NaN,ABRAHAM,NaN,JOS,H,26
26,API,FEMALE,2014-04-28,1986,POLICE OFFICER,2014-04-28,ABRAHAM,NaN,NANCY,A,27
27,BLACK,MALE,2016-06-27,1988,POLICE OFFICER,2016-06-27,ABRAM,NaN,ANTHONY,A,28
28,BLACK,MALE,1976-04-26,1939,SERGEANT OF POLICE,1991-02-16,ABRAM,NaN,PAUL,W,29
29,BLACK,MALE,1986-06-16,1963,POLICE OFFICER,1986-06-16,ABRAMS,NaN,HENRY,L,30
...,...,...,...,...,...,...,...,...,...,...,...
31903,HISPANIC,MALE,1999-10-25,1968,POLICE OFFICER,1999-10-25,ZUNIGA,NaN,RONALD,NaN,31904
31904,WHITE,FEMALE,2014-09-29,1989,POLICE OFFICER,2014-09-29,ZUPANCIC,NaN,KELLY,L,31905
31905,WHITE,MALE,2012-12-14,1983,POLICE OFFICER,2012-12-14,ZUPANCIC,NaN,MICHAEL,P,31906
31906,WHITE,MALE,1970-12-14,1948,PO (PER ARB AWARD),1970-12-14,ZUR,NaN,PETER,NaN,31907
31907,WHITE,MALE,1953-09-21,1927,POLICE OFFICER,1953-09-21,ZURALES,NaN,LEONARD,NaN,31908
31908,WHITE,FEMALE,1980-09-29,1954,POLICE OFFICER,1980-09-29,ZURAWIK,NaN,DEBORAH,M,31909
31909,WHITE,MALE,1977-04-04,1953,PO AS DETECTIVE,1977-04-04,ZURAWIK,NaN,JAMES,E,31910
31910,WHITE,MALE,1961-05-29,1935,CAPTAIN OF POLICE,1977-10-16,ZURAWSKI,NaN,JAMES,J,31911
31911,WHITE,MALE,1970-06-15,1949,POLICE OFFICER,1970-06-15,ZURAWSKI,NaN,JAMES,G,31912
31912,WHITE,FEMALE,1991-04-24,1962,POLICE OFFICER,1991-04-24,ZURAWSKI,NaN,MARY,E,31913
31913,WHITE,MALE,1991-01-02,1957,POLICE OFFICER,1991-01-02,ZUREK,NaN,GREGORY,M,31914
31914,HISPANIC,MALE,2014-10-27,1990,POLICE OFFICER,2014-10-27,ZURITA,NaN,ADRIEL,,31915
31915,HISPANIC,FEMALE,2006-11-27,1974,POLICE OFFICER,2006-11-27,ZURITA,NaN,YVETTE,D,31916
31916,WHITE,MALE,1968-03-04,1947,POLICE OFFICER,1968-03-04,ZUZICH,NaN,JOSEPH,C,31917
31917,WHITE,MALE,1955-02-01,1929,PO AS DETECTIVE,1955-02-01,ZWIER,NaN,HENRY,S,31918
31918,WHITE,MALE,1973-03-19,1951,PO AS DETECTIVE,1973-03-19,ZWIT,NaN,JAMES,R,31919
31919,WHITE,MALE,2002-05-28,1979,POLICE OFFICER,2002-05-28,ZWIT,NaN,JEFFREY,J,31920
31920,WHITE,FEMALE,1997-09-02,1967,POLICE OFFICER,1997-09-02,ZWOLSKI,NaN,MARY,L,31921
31921,WHITE,MALE,1946-03-11,1916,UNKNOWN,NaN,ZYCH,NaN,ADAM,J,31922
31922,WHITE,MALE,1961-01-09,1933,POLICE OFFICER,1961-01-09,ZYCH,NaN,HENRY,A,31923
31923,WHITE,MALE,2015-08-31,1990,POLICE OFFICER,2015-08-31,ZYCH,NaN,MATEUSZ,M,31924
31924,WHITE,MALE,2007-09-24,1984,POLICE OFFICER,2007-09-24,ZYDEK,NaN,BRYAN,L,31925
31925,WHITE,MALE,2016-02-29,1990,POLICE OFFICER,2016-02-29,ZYGMUNT,NaN,DAWID,NaN,31926
31926,WHITE,MALE,1966-05-09,1941,POLICE OFFICER,1966-05-30,ZYGOWICZ,NaN,JAMES,NaN,31927
31927,WHITE,MALE,1999-04-01,1970,POLICE OFFICER,1999-04-01,ZYGOWICZ,NaN,PETER,J,31928
31928,WHITE,FEMALE,2016-02-29,1980,POLICE OFFICER,2001-01-01,ZYLINSKA,NaN,KATARZYNA,,31929
31929,WHITE,FEMALE,1986-10-13,1956,PO AS DETECTIVE,1986-10-13,ZYLVITIS,NaN,DEBRA,A,31930
31930,WHITE,MALE,2002-12-02,1974,POLICE OFFICER,2002-12-02,ZYMANTAS,NaN,MARK,E,31931
31931,WHITE,MALE,1996-12-02,1970,POLICE OFFICER,1996-12-02,ZYRKOWSKI,NaN,CARLO,E,31932
31932,WHITE,MALE,1955-02-08,1932,PO AS DETECTIVE,1955-02-08,ZYSKOWSKI,NaN,STANLEY,H,31933